# Welcome to Beautiful Jekyll!
# This config file is meant for settings that affect your entire website. When you first
# set up your website you should go through all these settings and edit them, but after
# the initial set up you won't need to come back to this file often.

# --- Required options --- #

# Name of website
title: Aarif's Site

# Your name to show in the footer
author: Aarif Razak

theme: jekyll-theme-minimal
logo: aarif_washington_square_Park.jpg
description: Thrilled about NYC Weather
# --- Footer social media links --- #

# Select the social network links that you want to show in the footer.
# Uncomment the links you want to show and add your information to each one.
social-network-links:
  github: aarif-razak
  twitter: aarif_razak
